- CONTRIBUTORS.md
- profiles/Rushi_Patel.md
- scripts/CheckPythogorianTriplets_Developer-R-7.cpp
2 files added (Rushi_Patel.md,CheckPythogorianTriplets_Developer-R-7.cpp) and 1 file changed (contributors.md) 
Happy coding :), Hope you will merge my pull request
> Added CheckPythogorianTriplets.cpp ,modified contributors.md and added profile 

- CONTRIBUTORS.md
- profiles/Munish_Kumar.md
- scripts/HelloWorldbyMunish.py
> Add profile to repo

- scripts/DecimalToBinary.cpp
**If you don't mind I would like to submit my more amazing works and script to  your repo**
This Program take integer value from user and changed it to binary "0s and 1s" 
Happy Coding  :)
> Added "DecimalToBinary.cpp" 

- scripts/IsArmstrongNumber.cpp
Eg: 153 is a Armstrong number
**Condition to be Armstrong number**
**1**^3 + **5**^3 + **3**^3 (sum of digits raised to the power 3 is equal to the number itself)   = 153
Happy Coding! :)
> Added a c++ scripts that check if a number is armstrong number or not

- CONTRIBUTORS.md
- profiles/Ajay_Kumar.md
- scripts/Join2AJ_Video_to_Audio_Conversation.py
Convert video files to wav-audio format and listen news or motivational speech or information content or prepare for exams !
> Video to Audio conversation

- CONTRIBUTORS.md
- profiles/Suman_Chandra.md
- scripts/Hello_World_sumannitp.java
Sir I have done everything according to instruction . Please merge it.
> Added name to contributors.ms,added new profile page and also added code to script 

- CONTRIBUTORS.md
- profiles/KavesshaGallage.md
- scripts/Hello_World_KaveeshaGallage.java
Hi there,
Please accept my PR. Best wishes for your future works!
> Task completed-Kaveesha Gallage

- CONTRIBUTORS.md
- profiles/William_Kourafas.md
- scripts/Hello_world.cpp
Added a bio, added my name to contributors, and created a simple "Hello world" program in cpp.
> Added Bio and Hello world script

- CONTRIBUTORS.md
- profiles/Ankit_Gupta.md
- scripts/Hello_World_ankit-95.java
Completed all the 3 tasks.
@Nihal-Priyadarshi 
Please review my PR and merge it.
> Tower of Hanoi Problem [Asked in FAANG Interview][Completed all the 3 tasks]

- CONTRIBUTORS.md
- profiles/Shubhangi_Dwivedi.md
- scripts/Transpose_Matrix_shubhangi-dwivedi.cpp
Please merge my PR. Complete all 3 tasks.
> All tasks completed

- scripts/SimpleSorting.java
> Simple sorting algorithms java implementation

- profiles/jyoti pandey
>  jyoti pandey

- scripts/rotate screen jyotip31
created a rotate screen program
> rotate screen jyotip31

- scripts/Calculator.java
> Java simple calculator application

- CONTRIBUTORS.md
- profiles/vanshikagoel
- scripts/FIBONACCI SERIES
> HACKTOBERFEST

- scripts/OrderedArray
Please accept my PR. Thanks in advance.
> ordered array implementation java

- CONTRIBUTORS.md
- profiles/Siddharth_Borman.md
- scripts/Hello_World_PricelessBread.java
Completed all the three given tasks !
> Hacktober 2021 

- CONTRIBUTORS.md
- RAshid602.md
- profiles/Rashid
- scripts/HelloWorld_by_RAshid602
- scripts/RAshid602
- scripts/nextpermutation.java
> updated profie

- profiles/Keinisha.md
> Created Keinisha.md

- scripts/Hello_world_keinisha.c
> Created Hello World
